[project]
name = "bhoovalaya"
version = "1.0.0"
requires-python = ">=3.10"
[project]
name = "bhoovalaya-oracle"
version = "0.1.0"
dependencies = [
    "flet",
    "swisseph-ffi",
]
[tool.flet]
org = "com.flet"
product = "my3rd"
company = "my3rd"

[tool.flet.android]
permissions = ["android.permission.INTERNET"]
